// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEARgCMkWQ-2BTWzIAK-K1JfTDqckLNBY',
    appId: '1:281740730063:web:5750ee4a924febc56461ba',
    messagingSenderId: '281740730063',
    projectId: 'yanbaru-hackathon',
    authDomain: 'yanbaru-hackathon.firebaseapp.com',
    storageBucket: 'yanbaru-hackathon.appspot.com',
    measurementId: 'G-P317G7X3KR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPCwiVQcEeHRMhm4j2HOV1n1k5GjmE94M',
    appId: '1:281740730063:android:db18f1e499e78d816461ba',
    messagingSenderId: '281740730063',
    projectId: 'yanbaru-hackathon',
    storageBucket: 'yanbaru-hackathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwTPS1JbpKwPqSV2mQWzLXX-Pq1sb_9P0',
    appId: '1:281740730063:ios:91b4fa235e89ba446461ba',
    messagingSenderId: '281740730063',
    projectId: 'yanbaru-hackathon',
    storageBucket: 'yanbaru-hackathon.appspot.com',
    iosBundleId: 'com.example.yanbaruHackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwTPS1JbpKwPqSV2mQWzLXX-Pq1sb_9P0',
    appId: '1:281740730063:ios:f98a6ea62fe98c676461ba',
    messagingSenderId: '281740730063',
    projectId: 'yanbaru-hackathon',
    storageBucket: 'yanbaru-hackathon.appspot.com',
    iosBundleId: 'com.example.yanbaruHackathon.RunnerTests',
  );
}
